name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: |
          sudo apt-get update

      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no root@65.0.85.246 "
            cd /var/www/Blog-Backend && \
            git pull origin main && \
            composer install --no-dev --optimize-autoloader && \
            npm install \
            npm run build \
            php artisan config:cache && \
            php artisan route:cache
          "
